// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANiAXLDuZDnk_IVGq8npfmZSWGQ9Xsm88',
    appId: '1:369573824652:web:570f40c6caca34411293a9',
    messagingSenderId: '369573824652',
    projectId: 'dental-79d1b',
    authDomain: 'dental-79d1b.firebaseapp.com',
    databaseURL: 'https://dental-79d1b-default-rtdb.firebaseio.com',
    storageBucket: 'dental-79d1b.appspot.com',
    measurementId: 'G-57TLVB6CF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97s2BeRilF-F0jPJAFVH_K_XdYFOetqk',
    appId: '1:369573824652:android:d330489f3d6903bd1293a9',
    messagingSenderId: '369573824652',
    projectId: 'dental-79d1b',
    databaseURL: 'https://dental-79d1b-default-rtdb.firebaseio.com',
    storageBucket: 'dental-79d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeXXSAgvMfDhfp7tQPt6huAj1YJ66YYg',
    appId: '1:369573824652:ios:36c4a0da0efaa9501293a9',
    messagingSenderId: '369573824652',
    projectId: 'dental-79d1b',
    databaseURL: 'https://dental-79d1b-default-rtdb.firebaseio.com',
    storageBucket: 'dental-79d1b.appspot.com',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfeXXSAgvMfDhfp7tQPt6huAj1YJ66YYg',
    appId: '1:369573824652:ios:36c4a0da0efaa9501293a9',
    messagingSenderId: '369573824652',
    projectId: 'dental-79d1b',
    databaseURL: 'https://dental-79d1b-default-rtdb.firebaseio.com',
    storageBucket: 'dental-79d1b.appspot.com',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANiAXLDuZDnk_IVGq8npfmZSWGQ9Xsm88',
    appId: '1:369573824652:web:a50821904dbc39f01293a9',
    messagingSenderId: '369573824652',
    projectId: 'dental-79d1b',
    authDomain: 'dental-79d1b.firebaseapp.com',
    databaseURL: 'https://dental-79d1b-default-rtdb.firebaseio.com',
    storageBucket: 'dental-79d1b.appspot.com',
    measurementId: 'G-6RBQSJVBMW',
  );
}
